apiVersion: v1
kind: Service
metadata:
  name: service-fiap-grupo26
  namespace: mbaaso-grupo26
spec:
  selector:
    name: deployment-fiap-grupo26
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
